name: Auto Update ASN Lists

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

  push:
    branches: [ main, master ]

jobs:
  update-asn:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run ASN fetcher script
      run: |
        python ASN_Multiple_Countries.py
        
    - name: Check for changes
      id: check_changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "发现文件更新"
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "没有文件更新"
        fi
        
    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add ASN/

        git commit -m "Auto update ASN lists - $(date +'%Y-%m-%d %H:%M:%S UTC')" || exit 0

        git push
        
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: asn-files-${{ github.run_number }}
        path: ASN/
        retention-days: 30
        
    - name: Create release on major updates
      if: steps.check_changes.outputs.changes == 'true' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: asn-update-${{ github.run_number }}
        name: ASN Update ${{ github.run_number }}
        body: |
          自动更新的ASN列表文件
          
          更新时间: ${{ github.run_time }}
          
          本次更新包含所有支持国家的ASN信息。
        draft: false
        prerelease: false
        files: ASN/*
